replicaCount: 1

image:
  repository: vectornguyen76/image-search-engine
  # Always and latest for dev, IfNotPresent for prod
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 7000

env:
  - name: QDRANT_URL
    value: "http://qdrant-db.default:6334"
  - name: TRITON_SERVER_URL
    value: "search-engine-serving-triton-inference-server.default:8001"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

affinity: {}
# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: nodegroup-type
#               operator: In
#               values:
#                 - cpu-nodegroup