version: "3"
services:
  triton-server:
    container_name: triton-server
    image: nvcr.io/nvidia/tritonserver:23.09-py3
    ports:
      - 9000:8000
      - 9001:8001
      - 9002:8002
    command: tritonserver --model-repository=/models
    volumes:
      - ./image-search-engine/model_repository:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  qdrant-vector-database:
    container_name: qdrant-vector-database
    image: qdrant/qdrant:v1.5.1
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant-vector-database:/qdrant/storage

  image-search-engine:
    container_name: image-search-container
    image: vectornguyen76/image-search-engine
    build:
      context: ./image-search-engine
      dockerfile: Dockerfile
    environment:
      - QDRANT_URL=http://qdrant-vector-database:6334
      - TRITON_SERVER_URL=triton-server:8001
    ports:
      - 7000:7000
    volumes:
      - ./image-search-engine/logs:/app/logs
    depends_on:
      - qdrant-vector-database

  # image-search-engine-gpu:
  #   container_name: image-search-container-gpu
  #   image: vectornguyen76/image-search-engine-gpu
  #   build:
  #     context: ./image-search-engine
  #     dockerfile: Dockerfile.gpu
  #   environment:
  #     - QDRANT_URL=http://qdrant-vector-database:6334
  #     - TRITON_SERVER_URL=triton-server:8001
  #   ports:
  #     - 7000:7000
  #   volumes:
  #     - ./image-search-engine/logs:/app/logs
  #   depends_on:
  #     - qdrant-vector-database
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

volumes:
  qdrant-vector-database:
    driver: local
