version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    healthcheck:
        test: curl --fail http://localhost:9200/_cat/health || exit 1
        interval: 10s
        timeout: 1s
        retries: 10
    volumes:
      - data-elastic-search:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy

  image_search:
    container_name: image_search_container
    image: vectornguyen76/image_search_img
    build:
      context: ./image-search-engine
      dockerfile: Dockerfile
    ports:
      - 7000:7000

  text_search:
    container_name: text_search_container
    image: vectornguyen76/text_search_img
    build:
      context: ./text-search-engine
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      ELASTICSEARCH_HOST: http://elasticsearch:9200
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy

  frontend_service:
    container_name: frontend_container
    image: vectornguyen76/frontend_image
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 3000:3000

  nginx_service:
    container_name: nginx_container
    image: nginx:1.25.1-alpine
    ports:
      - 80:80
    volumes:
      - ./server/default.conf:/etc/nginx/conf.d/default.conf
      - ./server/log:/var/log/nginx/
    depends_on:
      - frontend_service

volumes:
  data-elastic-search:
    driver: local

networks:
  elastic:
    driver: bridge
