version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    healthcheck:
      test: curl --fail http://localhost:9200/_cat/health || exit 1
      interval: 10s
      timeout: 1s
      retries: 10
    volumes:
      - elastic_search_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy

  text-search-engine:
    container_name: text-search-container
    image: vectornguyen76/text-search-engine
    build:
      context: ./text-search-engine
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      ELASTICSEARCH_HOST: http://elasticsearch:9200
    volumes:
      - ./text-search-engine/logs:/app/logs
    depends_on:
      elasticsearch:
        condition: service_healthy

  image-search-engine:
    container_name: image-search-container
    image: vectornguyen76/image-search-engine
    build:
      context: ./image-search-engine
      dockerfile: Dockerfile
    environment:
      - QDRANT_URL=http://qdrant-db:6334
      - TRITON_SERVER_URL=triton-server:8001
    ports:
      - 7000:7000
    volumes:
      - ./image-search-engine/logs:/app/logs

  backend_service:
    container_name: backend_container
    image: backend_image
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.local
    ports:
      - 5000:5000
    volumes:
      - ./backend/logs/api.log:/app/logs/api.log

  db_service:
    container_name: db_container
    image: postgres:14.1
    env_file:
      - ./backend/.env.local
    ports:
      - 65432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
      - postgresql_data_backups:/backups
      - ./backend/scripts/postgres:/scripts

volumes:
  elastic_search_data:
    driver: local
  postgresql_data:
    driver: local
  postgresql_data_backups:
    driver: local
