apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-search-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-search
  template:
    metadata:
      labels:
        app: image-search
    spec:
      containers:
        - name: image-search-container
          image: vectornguyen76/image-search-engine:latest
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: QDRANT_HOST
              value: "qdrant-vector-database.default"
