apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: standard
  storageClassName: gp3 # Change to an EBS-provisioning StorageClass
  resources:
    requests:
      storage: 1Gi
