replicaCount: 1

image:
  repository: vectornguyen76/text-search-engine
  # Always and latest for dev, IfNotPresent for prod
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 8000

env:
  - name: ELASTICSEARCH_HOST
    value: "elasticsearch.database"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}