name: development
on: 
  pull_request:
    branches: develop

  push:
    branches:
      - develop
jobs:
  build-push-image-search:
    runs-on: ubuntu-latest
    env:	
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        id: docker_hub_auth
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./image-search-engine
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/image_search_img:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Cache Docker layers
      #   id: cache-docker
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/.docker
      #     key: ${{ runner.os }}-docker-${{ hashFiles('**/image-search-engine/Dockerfile') }}

      # - name: Build Docker Image
      #   id: build_docker
      #   run: |
      #     docker compose build image_search
          
      #     # Add tag
      #     docker tag image_search_img:latest ${{ secrets.DOCKERHUB_USERNAME }}/image_search_img:latest

      # - name: Push Docker Image
      #   id: push_images
      #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/image_search_img:latest

  build-push-text-search:
    runs-on: ubuntu-latest
    env:	
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2      

      - name: Login to Docker Hub
        id: docker_hub_auth
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  

      - name: Cache Docker layers
        id: cache-docker
        uses: actions/cache@v2
        with:
          path: |
            ~/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/text-search-engine/Dockerfile') }}

      - name: Build Docker Image
        id: build_docker
        run: |
          docker compose build text_search
          
          # Add tag
          docker tag text_search_img:latest ${{ secrets.DOCKERHUB_USERNAME }}/text_search_img:latest

      - name: Push Docker Image
        id: push_images
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/text_search_img:latest