name: development
on: 
  pull_request:
    branches: develop

  push:
    branches:
      - develop
jobs:
  build-push-image-search:
    runs-on: ubuntu-latest
    env:	
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        id: docker_hub_auth
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./image-search-engine
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/image_search_img:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-push-text-search:
    runs-on: ubuntu-latest
    env:	
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        id: docker_hub_auth
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./text-search-engine
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/text_search_img:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max