name: development
on: 
  pull_request:
    branches: develop

  push:
    branches:
      - develop
jobs:
  build-test-push-image-search:
    runs-on: ubuntu-latest
    env:	
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt

      - name: Run pylint
        run: |
          cd image-search-engine
          pylint service.py --disable=R,C,W1203

      - name: Login to Docker Hub
        id: docker_hub_auth
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  

      - name: Build Docker Image
        id: build_docker
        run: |
          docker compose build image_search
          
          # Add tag
          docker tag image_search_img:latest ${{ secrets.DOCKERHUB_USERNAME }}/image_search_img:latest

      - name: Push Docker Image
        id: push_images
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/image_search_img:latest
